package com.sibim.service;

import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.List;
import com.itextpdf.layout.element.ListItem;
import com.itextpdf.layout.element.Paragraph;
import com.sibim.util.UpdateChecker;

import java.io.File;

/**
 * "Guía rápida": the one-page-per-topic sheet for the áreas' staff — how to
 * sign in with the shared account, what works without internet, transfers,
 * formats and updates. Generated by the app so it always matches the
 * installed version; printable from the user menu.
 */
public class ReporteGuiaRapidaService extends ReporteService {

    private static final DeviceRgb TEXTO = new DeviceRgb(30, 41, 59);

    private static final String[][] SECCIONES = {
        {"1. Entrar al sistema",
            "Cada área tiene una sola cuenta (usuario y contraseña) que usa todo su personal, en cualquier computadora.",
            "Al entrar, escribe tu nombre: así queda registrado quién hizo cada cambio.",
            "La primera vez en cada computadora hay que entrar CON internet; después ya funciona sin conexión hasta por 30 días.",
            "La contraseña del área solo la cambia Recursos Materiales y Patrimonio. Si se te olvida, pídesela a Patrimonio."},
        {"2. Sin internet",
            "Si se va el internet, aparece la franja amarilla \"Sin conexión\" y puedes seguir trabajando.",
            "Todo lo que captures (bienes, resguardos, préstamos, comodatos, actas) se guarda en la computadora y se sube solo al volver la conexión.",
            "Mientras no haya conexión, los documentos nuevos llevan un folio provisional (por ejemplo RSG-PROV-3F2A1C); el folio definitivo se asigna al sincronizar.",
            "Sin conexión solo ves lo que esa computadora ya había consultado con internet."},
        {"3. Mis bienes",
            "En Bienes ves los bienes de tu área y puedes actualizar sus datos (ubicación, descripción, fotos, estado físico).",
            "Dar de alta, dar de baja y los movimientos los hace Patrimonio.",
            "Para pedir una baja: selecciona el bien > Exportar > \"Solicitud de baja (PDF)\" y, si el área técnica lo revisó, \"Dictamen técnico de baja (PDF)\". Firma y entrega ambos a Patrimonio.",
            "La etiqueta de cada bien tiene un código QR: al escanearlo con la cámara de cualquier celular se ve su ficha."},
        {"4. Transferencias entre áreas",
            "Para mover un bien a otra área: Bienes > selecciona el bien > \"Solicitar transferencia\" y elige el área destino.",
            "La solicitud espera la aprobación de Patrimonio (puedes verla en Movimientos > \"Mis solicitudes\").",
            "El área que recibe ve el aviso \"Bienes por recibir\" (campana y Movimientos > \"Por recibir\") y confirma cuando tiene el bien físicamente."},
        {"5. Resguardos, préstamos y comodatos",
            "Los resguardos, préstamos y comodatos se consultan e imprimen en su sección.",
            "Solo Patrimonio los registra, cancela o cierra.",
            "Para pedir un préstamo o un resguardo: Bienes > clic derecho sobre el bien > \"Solicitar préstamo\" o \"Solicitar resguardo\".",
            "La respuesta de Patrimonio aparece en Préstamos (o Resguardos) > \"Mis solicitudes\"."},
        {"6. Actualizaciones",
            "Cuando hay una versión nueva, al abrir SIBIM aparece \"Nueva versión disponible\". Da clic en \"Instalar\": se descarga, se abre el instalador y SIBIM se cierra. Guarda antes lo que estés capturando.",
            "Si Windows muestra \"Windows protegió su PC\", da clic en \"Más información\" y luego en \"Ejecutar de todas formas\"."},
        {"Solo para Patrimonio (administrador)",
            "Movimientos > \"Pendientes\": aprueba o rechaza las transferencias que piden las áreas.",
            "Préstamos o Resguardos > \"Solicitudes\": aprueba (se crea el documento) o rechaza con motivo lo que piden las áreas.",
            "Bajas: solo con la solicitud firmada del área; anota su folio al dar de baja.",
            "Configuración > Usuarios > \"Cuentas por área\": crea las cuentas que falten y genera el PDF con contraseñas.",
            "Configuración > \"Publicar actualización\": sube el instalador de una versión nueva (primero sube la versión en pom.xml y genera el instalador en esta PC, que es la que actualiza la base)."},
    };

    public File exportGuia() throws Exception {
        File file = tempFile("guia_rapida_sibim", ".pdf");
        PdfFont bold = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);
        PdfFont reg  = PdfFontFactory.createFont(StandardFonts.HELVETICA);
        try (PdfWriter writer = new PdfWriter(file.getAbsolutePath());
             PdfDocument pdf = new PdfDocument(writer);
             Document doc = new Document(pdf, PageSize.LETTER)) {
            doc.setMargins(30, 40, 30, 40);
            addPdfHeader(doc, "Guía rápida de SIBIM · v" + UpdateChecker.currentVersion(), null, null);
            for (String[] s : SECCIONES) {
                doc.add(sectionTitle(s[0].toUpperCase(), bold, COLOR_HEADER).setFontSize(10f).setMarginTop(8));
                List lista = new List().setSymbolIndent(10).setListSymbol("•").setFont(reg).setFontSize(9.5f)
                    .setFontColor(TEXTO);
                for (int i = 1; i < s.length; i++) lista.add(new ListItem(s[i]));
                doc.add(lista);
            }
            doc.add(new Paragraph("¿Dudas o algo no funciona? Comunícate con Recursos Materiales y Patrimonio.")
                .setFont(bold).setFontSize(9.5f).setMarginTop(14));
        }
        return file;
    }
}
