package com.sibim.db.integration;

import com.sibim.model.ActaEntregaRecepcion;
import com.sibim.repository.ActaRepository;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests for {@link ActaRepository} against an embedded PostgreSQL.
 *
 * actas_entrega_recepcion has no FK to products — only to users(id) via
 * creado_por_id (ON DELETE SET NULL), so no product/category setup is needed.
 * The admin user is seeded by IntegrationTestBase.truncateAll().
 */
class ActaRepositoryIntegrationTest extends IntegrationTestBase {

    private final ActaRepository repo = new ActaRepository();

    // ── Helper ────────────────────────────────────────────────────────────────

    private ActaEntregaRecepcion buildActa(String saliente, String entrante, LocalDate fecha) {
        ActaEntregaRecepcion a = new ActaEntregaRecepcion();
        a.setAdminSaliente(saliente);
        a.setCargoSaliente("Presidente Municipal Saliente");
        a.setAdminEntrante(entrante);
        a.setCargoEntrante("Presidente Municipal Entrante");
        a.setFechaEntrega(fecha);
        a.setTotalBienes(42);
        a.setValorTotal(BigDecimal.valueOf(1_250_000));
        a.setObservaciones("Entrega sin observaciones relevantes");
        return a;
    }

    // ── Tests ─────────────────────────────────────────────────────────────────

    /**
     * A saved acta must be retrievable via findAll() with the correct
     * adminSaliente and fechaEntrega values.
     */
    @Test
    void save_nuevaActa_persisteEnDB() throws SQLException {
        LocalDate hoy = LocalDate.now();
        ActaEntregaRecepcion saved = repo.save(buildActa("María Ríos", "Luis Hdez", hoy));

        assertNotNull(saved.getId(), "save debe asignar un id");
        assertNotNull(saved.getNumero(), "save debe asignar un número de folio");

        List<ActaEntregaRecepcion> all = repo.findAll();
        assertEquals(1, all.size());
        ActaEntregaRecepcion found = all.get(0);
        assertEquals("María Ríos", found.getAdminSaliente());
        assertEquals("Luis Hdez", found.getAdminEntrante());
        assertEquals(hoy, found.getFechaEntrega());
    }

    /**
     * The folio generated by save() must follow the AER-YYYY-NNNN format.
     */
    @Test
    void save_asignaFolioAER() throws SQLException {
        ActaEntregaRecepcion saved = repo.save(buildActa("A", "B", LocalDate.now()));
        assertTrue(saved.getNumero().startsWith("AER-"),
            "el folio del acta debe comenzar con AER-");
    }

    /**
     * Two consecutive saves must produce distinct sequential folio numbers.
     */
    @Test
    void save_dosActas_numerosSecuenciales() throws SQLException {
        ActaEntregaRecepcion a1 = repo.save(buildActa("Saliente 1", "Entrante 1", LocalDate.now()));
        ActaEntregaRecepcion a2 = repo.save(buildActa("Saliente 2", "Entrante 2", LocalDate.now()));
        assertNotEquals(a1.getNumero(), a2.getNumero(),
            "dos actas no pueden tener el mismo número de folio");
    }

    /**
     * totalBienes and valorTotal must round-trip through save → findAll correctly.
     */
    @Test
    void save_totalBienesYValor_persistenCorrectamente() throws SQLException {
        ActaEntregaRecepcion saved = repo.save(buildActa("A", "B", LocalDate.now()));

        try (Connection c = getConnection();
             PreparedStatement ps = c.prepareStatement(
                     "SELECT total_bienes, valor_total FROM actas_entrega_recepcion WHERE id = ?")) {
            ps.setString(1, saved.getId());
            try (ResultSet rs = ps.executeQuery()) {
                assertTrue(rs.next());
                assertEquals(42, rs.getInt("total_bienes"));
                assertEquals(0, BigDecimal.valueOf(1_250_000)
                    .compareTo(rs.getBigDecimal("valor_total")));
            }
        }
    }

    /**
     * save() must set creado_por_id from the session — the admin row seeded
     * in truncateAll must exist in users for the FK to satisfy.
     */
    @Test
    void save_creadoPorId_coincideConSesion() throws SQLException {
        ActaEntregaRecepcion saved = repo.save(buildActa("A", "B", LocalDate.now()));

        try (Connection c = getConnection();
             PreparedStatement ps = c.prepareStatement(
                     "SELECT creado_por_id FROM actas_entrega_recepcion WHERE id = ?")) {
            ps.setString(1, saved.getId());
            try (ResultSet rs = ps.executeQuery()) {
                assertTrue(rs.next());
                assertEquals("test-admin", rs.getString("creado_por_id"),
                    "creado_por_id debe ser el id del usuario de la sesión activa");
            }
        }
    }

    /**
     * findAll() on an empty table must return an empty list, never throw.
     */
    @Test
    void findAll_tablaVacia_retornaListaVacia() throws SQLException {
        List<ActaEntregaRecepcion> all = repo.findAll();
        assertNotNull(all);
        assertTrue(all.isEmpty());
    }

    /**
     * findAll() must return multiple actas ordered by created_at DESC
     * (most recently created first).
     */
    @Test
    void findAll_variasActas_retornaTodasOrdenadas() throws SQLException {
        repo.save(buildActa("Primera", "Primera E", LocalDate.now().minusDays(1)));
        repo.save(buildActa("Segunda", "Segunda E", LocalDate.now()));

        List<ActaEntregaRecepcion> all = repo.findAll();
        assertEquals(2, all.size());
    }
}
